name: Test and Deploy

on: [push]  # Exécuter sur les push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'  # Version de Python souhaitée

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-tests.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests -p "*.py"

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Exécuter ce job seulement si les tests réussissent

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Faire appel à l'API pour installer la nouvelle version
      - name: Call deployment API
        run: |
          response=$(curl -v -s -w "%{http_code}" -o response.json \
            -X POST http://109.176.197.102:5000/deploy \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN_DEPLOY }}" \
          ) 2> curl_errors.log
      
          echo "Response code: $response"
          echo "Response message:"
          cat response.json
          cat curl_errors.log

          if [ "$response" -ne 200 ]; then
            echo "Deployment failed with response code $response"
            exit 1
          fi

        shell: /bin/bash -e {0}

      # Appeler l'API pour redémarrer Gunicorn
      - name: Call restart API
        run: |
          curl -s -w "%{http_code}" -o response.json \
            -X POST http://109.176.197.102:5000/restart \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN_DEPLOY }}" \

      # Attendre que Gunicorn redémarre
      - name: Wait for Gunicorn to be online
        run: |
          attempt=0
          max_attempts=10
          service_up=false

          echo "Attendre 10 secondes avant de commencer les vérifications..."
          sleep 10

          while [ $attempt -lt $max_attempts ]; do
            response=$(curl -s -w "%{http_code}" -o /dev/null http://109.176.197.102:5000/health)
            if [ "$response" -eq 200 ]; then
              echo "Gunicorn est en ligne après $((attempt+1)) tentative(s)."
              service_up=true
              break
            fi
            echo "Gunicorn n'est pas encore prêt. Nouvelle tentative dans 10 secondes..."
            attempt=$((attempt+1))
            sleep 10
          done

          if [ "$service_up" = false ]; then
            echo "Erreur : Gunicorn n'a pas redémarré après $max_attempts tentatives."
            exit 1
          fi

      - name: Deploy success message
        if: success()
        run: echo "Deployment succeeded!"